//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.Date;

public class DemographicsType implements Serializable {
	
	private int patientId;
	
	private String firstName;
	
	private String lastName;
	
	private String middleName;
	
	private String gender;
	
	private Date birthdate;
	
	private int birthdateEstimated;
	
	private int dead;
	
	private Date deathDate;
	
	private String causeOfDeath;
	
	private int creator;
	
	private Date dateCreated;
	
	private String phoneNumber;
	
	private String address1;
	
	private String address2;
	
	private String cityVillage;
	
	private String stateProvince;
	
	private String country;
	
	private int changedBy;
	
	private Date dateChanged;
	
	private int voided;
	
	private int voidedBy;
	
	private Date dateVoided;
	
	private String voidedReason;
	
	private int deathdateEstimated;
	
	private String patientUuid;
	
	private String datimId;
	
	public int getPatientId() {
		return patientId;
	}
	
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}
	
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getMiddleName() {
		return middleName;
	}
	
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}
	
	public String getGender() {
		return gender;
	}
	
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public Date getBirthdate() {
		return birthdate;
	}
	
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}
	
	public int getBirthdateEstimated() {
		return birthdateEstimated;
	}
	
	public void setBirthdateEstimated(int birthdateEstimated) {
		this.birthdateEstimated = birthdateEstimated;
	}
	
	public int getDead() {
		return dead;
	}
	
	public void setDead(int dead) {
		this.dead = dead;
	}
	
	public Date getDeathDate() {
		return deathDate;
	}
	
	public void setDeathDate(Date deathDate) {
		this.deathDate = deathDate;
	}
	
	public String getCauseOfDeath() {
		return causeOfDeath;
	}
	
	public void setCauseOfDeath(String causeOfDeath) {
		this.causeOfDeath = causeOfDeath;
	}
	
	public int getCreator() {
		return creator;
	}
	
	public void setCreator(int creator) {
		this.creator = creator;
	}
	
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public String getPhoneNumber() {
		return phoneNumber;
	}
	
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	public String getAddress1() {
		return address1;
	}
	
	public void setAddress1(String address1) {
		this.address1 = address1;
	}
	
	public String getAddress2() {
		return address2;
	}
	
	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	
	public String getCityVillage() {
		return cityVillage;
	}
	
	public void setCityVillage(String cityVillage) {
		this.cityVillage = cityVillage;
	}
	
	public String getStateProvince() {
		return stateProvince;
	}
	
	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}
	
	public String getCountry() {
		return country;
	}
	
	public void setCountry(String country) {
		this.country = country;
	}
	
	public int getChangedBy() {
		return changedBy;
	}
	
	public void setChangedBy(int changedBy) {
		this.changedBy = changedBy;
	}
	
	public Date getDateChanged() {
		return dateChanged;
	}
	
	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}
	
	public int getVoided() {
		return voided;
	}
	
	public void setVoided(int voided) {
		this.voided = voided;
	}
	
	public int getVoidedBy() {
		return voidedBy;
	}
	
	public void setVoidedBy(int voidedBy) {
		this.voidedBy = voidedBy;
	}
	
	public Date getDateVoided() {
		return dateVoided;
	}
	
	public void setDateVoided(Date dateVoided) {
		this.dateVoided = dateVoided;
	}
	
	public String getVoidedReason() {
		return voidedReason;
	}
	
	public void setVoidedReason(String voidedReason) {
		this.voidedReason = voidedReason;
	}
	
	public int getDeathdateEstimated() {
		return deathdateEstimated;
	}
	
	public void setDeathdateEstimated(int deathdateEstimated) {
		this.deathdateEstimated = deathdateEstimated;
	}
	
	public String getPatientUuid() {
		return patientUuid;
	}
	
	public void setPatientUuid(String patientUuid) {
		this.patientUuid = patientUuid;
	}
	
	public String getDatimId() {
		return datimId;
	}
	
	public void setDatimId(String datimId) {
		this.datimId = datimId;
	}
}
