//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.Date;

public class EncounterProviderType implements Serializable {
	
	private int encounterProviderId;
	
	private int encounterId;
	
	private int providerId;
	
	private int locationId;
	
	private int encounterRoleId;
	
	private int creator;
	
	private Date dateCreated;
	
	private int changedBy;
	
	private Date dateChanged;
	
	private int voided;
	
	private Date dateVoided;
	
	private int voidedBy;
	
	private String voidedReason;
	
	private String encounterProviderUuid;
	
	private String datimId;
	
	private String patientUuid;
	
	private String encounterUuid;
	
	private String visitUuid;
	
	public int getEncounterProviderId() {
		return encounterProviderId;
	}
	
	public void setEncounterProviderId(int encounterProviderId) {
		this.encounterProviderId = encounterProviderId;
	}
	
	public int getEncounterId() {
		return encounterId;
	}
	
	public void setEncounterId(int encounterId) {
		this.encounterId = encounterId;
	}
	
	public int getProviderId() {
		return providerId;
	}
	
	public void setProviderId(int providerId) {
		this.providerId = providerId;
	}
	
	public int getLocationId() {
		return locationId;
	}
	
	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}
	
	public int getEncounterRoleId() {
		return encounterRoleId;
	}
	
	public void setEncounterRoleId(int encounterRoleId) {
		this.encounterRoleId = encounterRoleId;
	}
	
	public int getCreator() {
		return creator;
	}
	
	public void setCreator(int creator) {
		this.creator = creator;
	}
	
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public int getChangedBy() {
		return changedBy;
	}
	
	public void setChangedBy(int changedBy) {
		this.changedBy = changedBy;
	}
	
	public Date getDateChanged() {
		return dateChanged;
	}
	
	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}
	
	public int getVoided() {
		return voided;
	}
	
	public void setVoided(int voided) {
		this.voided = voided;
	}
	
	public Date getDateVoided() {
		return dateVoided;
	}
	
	public void setDateVoided(Date dateVoided) {
		this.dateVoided = dateVoided;
	}
	
	public int getVoidedBy() {
		return voidedBy;
	}
	
	public void setVoidedBy(int voidedBy) {
		this.voidedBy = voidedBy;
	}
	
	public String getVoidedReason() {
		return voidedReason;
	}
	
	public void setVoidedReason(String voidedReason) {
		this.voidedReason = voidedReason;
	}
	
	public String getEncounterProviderUuid() {
		return encounterProviderUuid;
	}
	
	public void setEncounterProviderUuid(String encounterProviderUuid) {
		this.encounterProviderUuid = encounterProviderUuid;
	}
	
	public String getDatimId() {
		return datimId;
	}
	
	public void setDatimId(String datimId) {
		this.datimId = datimId;
	}
	
	public String getPatientUuid() {
		return patientUuid;
	}
	
	public void setPatientUuid(String patientUuid) {
		this.patientUuid = patientUuid;
	}
	
	public String getEncounterUuid() {
		return encounterUuid;
	}
	
	public void setEncounterUuid(String encounterUuid) {
		this.encounterUuid = encounterUuid;
	}
	
	public String getVisitUuid() {
		return visitUuid;
	}
	
	public void setVisitUuid(String visitUuid) {
		this.visitUuid = visitUuid;
	}
}
