//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class MessageDataType implements Serializable {
	
	private DemographicsType demographics;
	
	private List<VisitType> visits;
	
	private List<EncounterType> encounters;
	
	private List<ObsType> obs;
	
	private List<EncounterProviderType> encounterProviders;
	
	private List<PatientIdentifierType> patientIdentifiers;
	
	private List<PatientBiometricType> patientBiometrics;
	
	private List<PatientProgramType> patientPrograms;
	
	public DemographicsType getDemographics() {
		return demographics;
	}
	
	public void setDemographics(DemographicsType demographics) {
		this.demographics = demographics;
	}
	
	public List<VisitType> getVisits() {
        if (visits == null)
            visits = new ArrayList<>();
        return visits;
    }
	
	public void setVisits(List<VisitType> visits) {
		this.visits = visits;
	}
	
	public List<EncounterType> getEncounters() {
        if (encounters == null)
            encounters = new ArrayList<>();
        return encounters;
    }
	
	public void setEncounters(List<EncounterType> encounters) {
		this.encounters = encounters;
	}
	
	public List<ObsType> getObs() {
        if (obs == null)
            obs = new ArrayList<>();
        return obs;
    }
	
	public void setObs(List<ObsType> obs) {
		this.obs = obs;
	}
	
	public List<EncounterProviderType> getEncounterProviders() {
        if (encounterProviders == null)
            encounterProviders = new ArrayList<>();
        return encounterProviders;
    }
	
	public void setEncounterProviders(List<EncounterProviderType> encounterProviders) {
		this.encounterProviders = encounterProviders;
	}
	
	public List<PatientIdentifierType> getPatientIdentifiers() {
        if (patientIdentifiers == null)
            patientIdentifiers = new ArrayList<>();
        return patientIdentifiers;
    }
	
	public void setPatientIdentifiers(List<PatientIdentifierType> patientIdentifiers) {
		this.patientIdentifiers = patientIdentifiers;
	}
	
	public List<PatientBiometricType> getPatientBiometrics() {
        if (patientBiometrics == null)
            patientBiometrics = new ArrayList<>();
        return patientBiometrics;
    }
	
	public void setPatientBiometrics(List<PatientBiometricType> patientBiometrics) {
		this.patientBiometrics = patientBiometrics;
	}
	
	public List<PatientProgramType> getPatientPrograms() {
        if (patientPrograms == null)
            patientPrograms = new ArrayList<>();
        return patientPrograms;
    }
	
	public void setPatientPrograms(List<PatientProgramType> patientPrograms) {
		this.patientPrograms = patientPrograms;
	}
}
