//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MessageHeaderType implements Serializable {
	
	private String messageStatusCode;
	
	private String messageSource;
	
	private Date messageCreationDateTime;
	
	private BigDecimal messageSchemaVersion;
	
	private String messageUniqueID;
	
	private String facilityDatimCode;
	
	private String facilityName;
	
	private String facilityLga;
	
	private String facilityState;
	
	private String fileName;
	
	private Date uploadDate;
	
	private Date processedDate;
	
	private int invalid;
	
	private String validationError;
	
	private Date touchTime;
	
	public String getMessageStatusCode() {
		return messageStatusCode;
	}
	
	public void setMessageStatusCode(String messageStatusCode) {
		this.messageStatusCode = messageStatusCode;
	}
	
	public String getMessageSource() {
		return messageSource;
	}
	
	public void setMessageSource(String messageSource) {
		this.messageSource = messageSource;
	}
	
	public Date getMessageCreationDateTime() {
		return messageCreationDateTime;
	}
	
	public void setMessageCreationDateTime(Date messageCreationDateTime) {
		this.messageCreationDateTime = messageCreationDateTime;
	}
	
	public BigDecimal getMessageSchemaVersion() {
		return messageSchemaVersion;
	}
	
	public void setMessageSchemaVersion(BigDecimal messageSchemaVersion) {
		this.messageSchemaVersion = messageSchemaVersion;
	}
	
	public String getMessageUniqueID() {
		return messageUniqueID;
	}
	
	public void setMessageUniqueID(String messageUniqueID) {
		this.messageUniqueID = messageUniqueID;
	}
	
	public String getFacilityDatimCode() {
		return facilityDatimCode;
	}
	
	public void setFacilityDatimCode(String facilityDatimCode) {
		this.facilityDatimCode = facilityDatimCode;
	}
	
	public String getFacilityName() {
		return facilityName;
	}
	
	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}
	
	public String getFacilityLga() {
		return facilityLga;
	}
	
	public void setFacilityLga(String facilityLga) {
		this.facilityLga = facilityLga;
	}
	
	public String getFacilityState() {
		return facilityState;
	}
	
	public void setFacilityState(String facilityState) {
		this.facilityState = facilityState;
	}
	
	public String getFileName() {
		return fileName;
	}
	
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	
	public Date getUploadDate() {
		return uploadDate;
	}
	
	public void setUploadDate(Date uploadDate) {
		this.uploadDate = uploadDate;
	}
	
	public Date getProcessedDate() {
		return processedDate;
	}
	
	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}
	
	public int getInvalid() {
		return invalid;
	}
	
	public void setInvalid(int invalid) {
		this.invalid = invalid;
	}
	
	public String getValidationError() {
		return validationError;
	}
	
	public void setValidationError(String validationError) {
		this.validationError = validationError;
	}
	
	public Date getTouchTime() {
		return touchTime;
	}
	
	public void setTouchTime(Date touchTime) {
		this.touchTime = touchTime;
	}
}
