//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.Date;

public class PatientProgramType implements Serializable {
	
	private int patientProgramId;
	
	private int patientId;
	
	private int programId;
	
	private int locationId;
	
	private String programName;
	
	private Date dateEnrolled;
	
	private Date dateCompleted;
	
	private int outcomeConceptId;
	
	private int creator;
	
	private Date dateCreated;
	
	private int changedBy;
	
	private Date dateChanged;
	
	private int voided;
	
	private int voidedBy;
	
	private Date dateVoided;
	
	private String patientUuid;
	
	private String datimId;
	
	private String patientProgramUuid;
	
	public int getPatientProgramId() {
		return patientProgramId;
	}
	
	public void setPatientProgramId(int patientProgramId) {
		this.patientProgramId = patientProgramId;
	}
	
	public int getPatientId() {
		return patientId;
	}
	
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}
	
	public int getProgramId() {
		return programId;
	}
	
	public void setProgramId(int programId) {
		this.programId = programId;
	}
	
	public int getLocationId() {
		return locationId;
	}
	
	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}
	
	public String getProgramName() {
		return programName;
	}
	
	public void setProgramName(String programName) {
		this.programName = programName;
	}
	
	public Date getDateEnrolled() {
		return dateEnrolled;
	}
	
	public void setDateEnrolled(Date dateEnrolled) {
		this.dateEnrolled = dateEnrolled;
	}
	
	public Date getDateCompleted() {
		return dateCompleted;
	}
	
	public void setDateCompleted(Date dateCompleted) {
		this.dateCompleted = dateCompleted;
	}
	
	public int getOutcomeConceptId() {
		return outcomeConceptId;
	}
	
	public void setOutcomeConceptId(int outcomeConceptId) {
		this.outcomeConceptId = outcomeConceptId;
	}
	
	public int getCreator() {
		return creator;
	}
	
	public void setCreator(int creator) {
		this.creator = creator;
	}
	
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public int getChangedBy() {
		return changedBy;
	}
	
	public void setChangedBy(int changedBy) {
		this.changedBy = changedBy;
	}
	
	public Date getDateChanged() {
		return dateChanged;
	}
	
	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}
	
	public int getVoided() {
		return voided;
	}
	
	public void setVoided(int voided) {
		this.voided = voided;
	}
	
	public int getVoidedBy() {
		return voidedBy;
	}
	
	public void setVoidedBy(int voidedBy) {
		this.voidedBy = voidedBy;
	}
	
	public Date getDateVoided() {
		return dateVoided;
	}
	
	public void setDateVoided(Date dateVoided) {
		this.dateVoided = dateVoided;
	}
	
	public String getPatientUuid() {
		return patientUuid;
	}
	
	public void setPatientUuid(String patientUuid) {
		this.patientUuid = patientUuid;
	}
	
	public String getDatimId() {
		return datimId;
	}
	
	public void setDatimId(String datimId) {
		this.datimId = datimId;
	}
	
	public String getPatientProgramUuid() {
		return patientProgramUuid;
	}
	
	public void setPatientProgramUuid(String patientProgramUuid) {
		this.patientProgramUuid = patientProgramUuid;
	}
}
