//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.Date;

public class PatientIdentifierType implements Serializable {
	
	private int patientIdentifierId;
	
	private int patientId;
	
	private int locationId;
	
	private String identifier;
	
	private int identifierType;
	
	private int preferred;
	
	private int creator;
	
	private Date dateCreated;
	
	private Date dateChanged;
	
	private int changedBy;
	
	private int voided;
	
	private int voidedBy;
	
	private Date dateVoided;
	
	private String patientIdentifierUuid;
	
	private String patientUuid;
	
	private String datimId;
	
	public int getPatientIdentifierId() {
		return patientIdentifierId;
	}
	
	public void setPatientIdentifierId(int patientIdentifierId) {
		this.patientIdentifierId = patientIdentifierId;
	}
	
	public int getPatientId() {
		return patientId;
	}
	
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}
	
	public int getLocationId() {
		return locationId;
	}
	
	public void setLocationId(int locationId) {
		this.locationId = locationId;
	}
	
	public String getIdentifier() {
		return identifier;
	}
	
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}
	
	public int getIdentifierType() {
		return identifierType;
	}
	
	public void setIdentifierType(int identifierType) {
		this.identifierType = identifierType;
	}
	
	public int getPreferred() {
		return preferred;
	}
	
	public void setPreferred(int preferred) {
		this.preferred = preferred;
	}
	
	public int getCreator() {
		return creator;
	}
	
	public void setCreator(int creator) {
		this.creator = creator;
	}
	
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public Date getDateChanged() {
		return dateChanged;
	}
	
	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}
	
	public int getChangedBy() {
		return changedBy;
	}
	
	public void setChangedBy(int changedBy) {
		this.changedBy = changedBy;
	}
	
	public int getVoided() {
		return voided;
	}
	
	public void setVoided(int voided) {
		this.voided = voided;
	}
	
	public int getVoidedBy() {
		return voidedBy;
	}
	
	public void setVoidedBy(int voidedBy) {
		this.voidedBy = voidedBy;
	}
	
	public Date getDateVoided() {
		return dateVoided;
	}
	
	public void setDateVoided(Date dateVoided) {
		this.dateVoided = dateVoided;
	}
	
	public String getPatientIdentifierUuid() {
		return patientIdentifierUuid;
	}
	
	public void setPatientIdentifierUuid(String patientIdentifierUuid) {
		this.patientIdentifierUuid = patientIdentifierUuid;
	}
	
	public String getPatientUuid() {
		return patientUuid;
	}
	
	public void setPatientUuid(String patientUuid) {
		this.patientUuid = patientUuid;
	}
	
	public String getDatimId() {
		return datimId;
	}
	
	public void setDatimId(String datimId) {
		this.datimId = datimId;
	}
}
