//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.06 at 02:19:42 AM WAT 
//

package org.openmrs.module.cdrsync.container.model;

import java.io.Serializable;
import java.util.Date;

public class PatientBiometricType implements Serializable {
	
	private int biometricInfoId;
	
	private int patientId;
	
	private String template;
	
	private int imageHeight;
	
	private int imageWidth;
	
	private int imageDpi;
	
	private int imageQuality;
	
	private String fingerPosition;
	
	private String serialNumber;
	
	private String model;
	
	private String manufacturer;
	
	private int creator;
	
	private Date dateCreated;
	
	private String patientUuid;
	
	private String datimId;
	
	public int getBiometricInfoId() {
		return biometricInfoId;
	}
	
	public void setBiometricInfoId(int biometricInfoId) {
		this.biometricInfoId = biometricInfoId;
	}
	
	public int getPatientId() {
		return patientId;
	}
	
	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}
	
	public String getTemplate() {
		return template;
	}
	
	public void setTemplate(String template) {
		this.template = template;
	}
	
	public int getImageHeight() {
		return imageHeight;
	}
	
	public void setImageHeight(int imageHeight) {
		this.imageHeight = imageHeight;
	}
	
	public int getImageWidth() {
		return imageWidth;
	}
	
	public void setImageWidth(int imageWidth) {
		this.imageWidth = imageWidth;
	}
	
	public int getImageDpi() {
		return imageDpi;
	}
	
	public void setImageDpi(int imageDpi) {
		this.imageDpi = imageDpi;
	}
	
	public int getImageQuality() {
		return imageQuality;
	}
	
	public void setImageQuality(int imageQuality) {
		this.imageQuality = imageQuality;
	}
	
	public String getFingerPosition() {
		return fingerPosition;
	}
	
	public void setFingerPosition(String fingerPosition) {
		this.fingerPosition = fingerPosition;
	}
	
	public String getSerialNumber() {
		return serialNumber;
	}
	
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}
	
	public String getModel() {
		return model;
	}
	
	public void setModel(String model) {
		this.model = model;
	}
	
	public String getManufacturer() {
		return manufacturer;
	}
	
	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}
	
	public int getCreator() {
		return creator;
	}
	
	public void setCreator(int creator) {
		this.creator = creator;
	}
	
	public Date getDateCreated() {
		return dateCreated;
	}
	
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}
	
	public String getPatientUuid() {
		return patientUuid;
	}
	
	public void setPatientUuid(String patientUuid) {
		this.patientUuid = patientUuid;
	}
	
	public String getDatimId() {
		return datimId;
	}
	
	public void setDatimId(String datimId) {
		this.datimId = datimId;
	}
}
